from .user import UserViewset
from .seccion import SeccionViewset
from .curso import CursoViewset
from .grado import GradoViewset
from .ciclo_escolar import CicloEscolarViewset
from .profesion import ProfesionViewset
from .tipouser import TipoUserViewset
from .eventos import EventosViewset
from .catedratico import CatedraticoViewset
from .estudiante import EstudianteViewset
from .asignacion import AsignacionViewset
from .nivel import NivelViewset
from .material_clase import MaterialClaseViewset
from .dashboardCatedratico import DashboardCatedraticoView