# Generated by Django 2.2.13 on 2021-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
