# Generated by Django 2.2.13 on 2021-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
