# Generated by Django 2.2.13 on 2021-02-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiluser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TipoUser')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Usuarios')),
            ],
        ),
    ]
