# Generated by Django 2.2.13 on 2021-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_perfiluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_seccion', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
