# Generated by Django 2.2.13 on 2021-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nivel', models.TextField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
