# Generated by Django 2.2.13 on 2021-02-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cicloescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cicloescolar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CicloEscolar')),
            ],
        ),
    ]
