# Generated by Django 2.2.13 on 2021-02-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
                ('apellidos', models.TextField(blank=True, max_length=30, null=True)),
                ('direecion', models.TextField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=12, null=True)),
                ('password_conf', models.CharField(blank=True, max_length=12, null=True)),
                ('tel_cont', models.IntegerField(blank=True, null=True)),
                ('dir_Cont', models.TextField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('perfil_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Perfiluser')),
            ],
        ),
    ]
