# Generated by Django 2.2.13 on 2021-02-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=12, null=True)),
                ('password_conf', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre', models.TextField(blank=True, max_length=30, null=True)),
                ('apellidos', models.TextField(blank=True, max_length=30, null=True)),
                ('direccion', models.TextField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('perfil_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Perfiluser')),
                ('profesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Profesion')),
            ],
        ),
    ]
