# Generated by Django 2.2.13 on 2021-02-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('catedratico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Catedratico')),
                ('cicloescolar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CicloEscolar')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
                ('grado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Grado')),
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Nivel')),
                ('seccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Seccion')),
            ],
        ),
    ]
