# Generated by Django 2.2.13 on 2021-02-15 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_estudianteasignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Estudiante')),
            ],
        ),
    ]
