# Generated by Django 2.2.13 on 2021-02-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Asignacion')),
            ],
        ),
    ]
