# Generated by Django 2.2.13 on 2021-02-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_materialclase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='cicloescolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CicloEscolar'),
        ),
    ]
