# Generated by Django 2.2.13 on 2021-02-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210226_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
