# Generated by Django 2.2.13 on 2021-02-26 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210226_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='perfil_user',
        ),
        migrations.AddField(
            model_name='catedratico',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
            preserve_default=False,
        ),
    ]
