# Generated by Django 2.2.13 on 2021-02-26 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210226_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='profile',
        ),
        migrations.AddField(
            model_name='catedratico',
            name='perfil_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Perfiluser'),
            preserve_default=False,
        ),
    ]
