# Generated by Django 2.2.13 on 2021-02-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210226_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='perfil_user',
        ),
        migrations.AddField(
            model_name='catedratico',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
