# Generated by Django 2.2.13 on 2021-03-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipouser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TipoUser'),
        ),
    ]
