# Generated by Django 2.2.13 on 2021-03-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='password',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='password_conf',
        ),
    ]
