# Generated by Django 2.2.13 on 2021-03-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210308_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catedratico',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='telefono',
        ),
    ]
