# Generated by Django 2.2.13 on 2021-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210309_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='direecion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='password',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='password_conf',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='telefono',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
