# Generated by Django 2.2.13 on 2021-03-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210309_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nombre',
        ),
    ]
