# Generated by Django 2.2.13 on 2021-03-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210310_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='catedratico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Catedratico'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='cicloescolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CicloEscolar'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Grado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nivel'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Seccion'),
        ),
    ]
