# Generated by Django 2.2.13 on 2021-03-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210316_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialclase',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivo_tarea'),
        ),
    ]
