# Generated by Django 2.2.13 on 2021-03-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210316_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialclase',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Asignacion'),
        ),
    ]
