from .profile import Profile
from .usuarios import Usuarios
from .tipouser import TipoUser
from .perfiluser import Perfiluser
from .seccion import Seccion
from .nivel import Nivel
from .grado import Grado
from .ciclo_escolar import CicloEscolar
from .eventos import Eventos
from .profesion import Profesion
from .estudiante import Estudiante
from .catedratico import Catedratico
from .curso import Curso
from .asignacion import Asignacion
from .estudiante_asignacion import EstudianteAsignacion
from .tarea_estudiante import TareaEstudiante
from .tareas import Tarea
from .material_clase import MaterialClase