from .user import UserSerializer, UserReadSerializer, ProfileSerializer
from .seccionSerializer import SeccionSerializer, SeccionRegistroSerializer
from .cursoSerializer import CursoSerializer, CursoRegistroSerializer
from .gradoSerailizer import GradoSerializer, GradoRegistroSerializer
from .ciclo_escolarSerializer import CicloEscolarSerializer, CicloEscolarRegistroSerializer
from .profesionSerializer import ProfesionSerializer, ProfesionRegistroSerializer
from .tipouserSerializer import TipoUserSerializer, TipoUserRegistroSerializer
from .eventosSerializer import EventosSerializer, EventosRegistroSerializer
from .catedraticoSerializer import CatedraticoSerializer, CatedraticoRegistroSerializer
from .estudianteSerializer import EstudianteSerializer, EstudianteRegistroSerializer
from .asigancionSerializer import AsignacionSerializer, AsignacionRegistroSerializer
from .nivelserializers import NivelSerializer, NivelRegistroSerializer
from .material_claseSerializers import MaterialClaseSerializer, MaterialClaseRegistroSerializer